config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'sessions/new'

  root :to => 'welcome#index', :as => 'home'
  resources :comments
  resources :ratings
  resources :users
  resources :books do
    resources :comments
    resources :ratings
  end
  resources :categories
  resources :sessions
  resources :welcome
  resources :for_sales

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/for_sale.rb
class ForSale < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_presence_of :price, :contact
  validates_numericality_of :price, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 999999
  validates_length_of :contact, :maximum => 255
end

app/controllers/for_sales_controller.rb
class ForSalesController < ApplicationController
  before_action :set_for_sale, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, :only=>[:show]

  # GET /for_sales
  # GET /for_sales.json
  def index
    @for_sales = ForSale.all
  end

  # GET /for_sales/1
  # GET /for_sales/1.json
  def show
  end

  # GET /for_sales/new
  def new
    @for_sale = ForSale.new
  end

  # GET /for_sales/1/edit
  def edit
    require_same_user(@for_sale.user_id)
  end

  # POST /for_sales
  # POST /for_sales.json
  def create
    @for_sale = ForSale.new(for_sale_params)
    @for_sale.user_id = current_user.id

    respond_to do |format|
      if @for_sale.save
        format.html { redirect_to @for_sale, success: 'For sale was successfully created.' }
        format.json { render :show, status: :created, location: @for_sale }
      else
        format.html { render :new }
        format.json { render json: @for_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /for_sales/1
  # PATCH/PUT /for_sales/1.json
  def update
    respond_to do |format|
      if @for_sale.update(for_sale_params)
        format.html { redirect_to @for_sale, success: 'For sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @for_sale }
      else
        format.html { render :edit }
        format.json { render json: @for_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /for_sales/1
  # DELETE /for_sales/1.json
  def destroy
    @for_sale.destroy
    respond_to do |format|
      format.html { redirect_to for_sales_url, info: 'For sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for_sale
      @for_sale = ForSale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def for_sale_params
      params.require(:for_sale).permit(:price, :contact, :user_id, :book_id)
    end
end

app/helpers/for_sales_helper.rb
module ForSalesHelper
end

app/views/for_sales/_for_sale.html.erb
<tbody>
    <tr>
      <td><%= for_sale.user.name %></td>
      <td><%= number_to_currency(for_sale.price, :unit => "kr ") %></td>
      <td><%= for_sale.contact %></td>
      <td><%= for_sale.book.title %></td>
      <td><%= link_to 'Show', for_sale %></td>
      <% if (current_user && (current_user.id == for_sale.user_id)) || current_admin %>
          <td><%= link_to 'Edit', edit_for_sale_path(for_sale) %></td>
          <td><%= link_to 'Destroy', for_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
</tbody>

app/views/for_sales/_form.html.erb
<%= form_with(model: for_sale, local: true) do |form| %>
    <% if for_sale.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <h4><%= pluralize(for_sale.errors.count, "error") %> prohibited this for_sale from being saved:</h4>

          <ul>
            <% for_sale.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= form.label :price %>
      <%= form.text_field :price , :class=>"form-control limit-form-width"%>
    </p>

    <p>
      <%= form.label 'Contact information' %>
      <%= form.text_area :contact , :class=>"form-control", :rows=>"5"%>
    </p>

      <%= form.hidden_field :book_id %>

      <%= form.hidden_field :user_id%>

    <%= form.submit 'Register book for sale', :class => 'btn btn-default', :id => 'submit_sell_book' %>

<% end %>

app/views/for_sales/edit.html.erb
<h1>Editing For Sale</h1>

<%= render 'form', for_sale: @for_sale %>

<%= link_to 'Show', @for_sale %> |
<%= link_to 'Back', for_sales_path %>

app/views/for_sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>For Sales</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Price</th>
      <th>Contact</th>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @for_sales.each do |for_sale| %>
      <tr>
        <td><%= number_to_currency(for_sale.price, :unit => "kr ") %></td>
        <td><%= for_sale.contact %></td>
        <td><%= for_sale.user.name %></td>
        <td><%= for_sale.book.title %></td>
        <td><%= link_to 'Show', for_sale %></td>
        <% if current_moderator || (current_user.id == for_sale.user_id) %>
            <td><%= link_to 'Edit', edit_for_sale_path(for_sale) %></td>
            <td><%= link_to 'Destroy', for_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/for_sales/new.html.erb
<h1>New For Sale</h1>

<%= render 'form', for_sale: @for_sale %>

<%= link_to 'Back', for_sales_path %>

app/views/for_sales/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">

  <h1>
    <%= @for_sale.book.title %>
  </h1>

  <div class="row">
    <div class="col-md-5">
      <table class="table ">
        <thead>
        <tr>
          <th>
            <strong>Price:</strong>
          </th>
          <th>
            <strong>Contact:</strong>
          </th>
          <th>
            <strong>User:</strong>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            <%= @for_sale.price %>
          </td>
          <td>
            <%= @for_sale.contact %>
          </td>
          <td>
            <%= @for_sale.user.name %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <p>
    <%= image_tag @for_sale.book.image %>
  </p>

  <% if current_user != nil && current_user.id == @for_sale.user.id %>
      <%= link_to 'Edit', edit_for_sale_path(@for_sale) %> |
  <% elsif current_admin %>
      <%= link_to 'Edit', edit_for_sale_path(@for_sale) %> |
  <% end %>
  <%= link_to 'Back', _back_url %>
</div>