config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'sessions/new'

  root :to => 'welcome#index', :as => 'home'
  resources :comments
  resources :ratings
  resources :users
  resources :books do
    resources :comments
    resources :ratings
  end
  resources :categories
  resources :sessions
  resources :welcome
  resources :for_sales

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :books
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_length_of :name, :maximum => 25
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_moderator, only: [:index, :edit, :update, :destroy, :new, :create]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_back(fallback_location: home_path,success: 'Category was successfully created.') }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_back(fallback_location: home_path,success: 'Category was successfully updated.') }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: home_path,info: 'Category was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:categoryId, :name, book_ids: [])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><strong><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved: </strong></p>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, :class => 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit :class =>'btn btn-default'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', _back_url %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>Categories</h1>
</div>
<table class ="table">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <% if current_moderator %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<div class="page-header">
<h1>New Category</h1>
</div>
<%= render 'form', category: @category %>

<%= link_to 'Back', _back_url %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>


<% if current_moderator %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', _back_url %>