config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'sessions/new'

  root :to => 'welcome#index', :as => 'home'
  resources :comments
  resources :ratings
  resources :users
  resources :books do
    resources :comments
    resources :ratings
  end
  resources :categories
  resources :sessions
  resources :welcome
  resources :for_sales

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syllabus</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'book_flat.ico' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top sidebar-nav">
  <div class="container-fluid">
    <div class="container">
      <%= link_to "Syllabus", home_path, class: 'navbar-brand' %>

      <!-- button for nav -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> <!-- end button for nav -->

      <!-- main navbar -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <%= form_tag home_path, :method => 'get', :class => 'navbar-form navbar-right' do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Search' %>
            </div>
            <%= submit_tag 'Search', :class => 'btn btn-default', :title => nil %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(home_path) %>"> <%= link_to 'Home', home_path %> </li>

          <% if current_moderator %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Moderator
                  links
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">

                  <% if current_admin %>
                      <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to 'Users', users_path %></li>
                  <% end %>

                  <li class="<%= 'active' if current_page?(comments_path) %>"> <%= link_to 'Comments', comments_path %></li>
                  <li class="<%= 'active' if current_page?(categories_path) %>"><%= link_to 'Categories', categories_path %></li>
                  <li class="<%= 'active' if current_page?(ratings_path) %>"><%= link_to 'Ratings', ratings_path %></li>
                  <li class="<%= 'active' if current_page?(books_path) %>"><%= link_to 'Books', books_path %></li>
                  <li class="<%= 'active' if current_page?(for_sales_path) %>"><%= link_to 'For Sale', for_sales_path %></li>
                </ul>
              </li>
          <% end %>

          <% if current_user %>
              <li class="<%= 'active' if current_page?(new_book_path) %>"> <%= link_to 'New Book', new_book_path %></li>
              <li onclick="history.go(0)"><%= link_to 'Log out', log_out_path %></li>
              <li class="<%= 'active' if current_page?(users_path + '/' + current_user.id.to_s) %>"> <%= link_to current_user.name, users_path + '/' + current_user.id.to_s %></li>
          <% else %>
              <li class="<%= 'active' if current_page?(sign_up_path) %>"><%= link_to 'Sign up', sign_up_path %></li>
              <li><a id="loginButton">Log in</a></li>
              <%= render 'sessions/form' %>
          <% end %>

        </ul>
      </div><!-- end main navbar -->
    </div> <!-- end container -->
  </div> <!-- end container fluid-->
</nav>
<div class="container">

  <%= yield %>

</div> <!-- end of container -->

<script>
    //Fixes boostrap dropdown in navbar
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>
</body>
</html>